### ISSUE TITLE
NPM contains incorrect version of code

### ISSUE THREAD

**Issue by shiftyp** [CFourPO/ts-swapi#1]
Hi, I've installed version 1.0.6 from NPM but it seems to be possibly an older version of the code than is contained in GitHub. Let me know if you need more information to help debug.

**Comment by CFourPO** [comment]
Hey @shiftyp thanks for creating this issue. I published a new version to npm v1.2.0. Give that a try and let me know if you have any questions! I am working on updating the README.md with more documentation on how to use the wrapper etc. Happy to hear you gave it a try!!

**Comment by CFourPO** [comment]
Closing this issue, definitely let me know if you run into any more issues @shiftyp

**Comment by shiftyp** [comment]
Thanks! 👍
